### ISSUE TITLE
RevGadgets archived on CRAN

### ISSUE THREAD

**Issue by willgearty** [revbayes/RevGadgets#14]
It looks like this package was archived on CRAN due to [failing various checks](https://cran-archive.r-project.org/web/checks/2022/2022-04-04_check_results_RevGadgets.html). Are there any plans to fix the package and restore it to CRAN? We'd really like to include the CRAN version in the new [phylogenetics CRAN task view](https://github.com/cran-task-views/Phylogenetics).

@cmt2

**Comment by cmt2** [comment]
Hi Will,

Thanks for the heads up. I had no idea that it had been removed from CRAN
and had received no messages about this. I'll definitely look into the
issues and try to get it restored.

cheers,
Carrie

-------------------
Carrie M. Tribble, PhD <http://carrietribble.weebly.com/> (she/her)
NSF Postdoctoral Fellow, Zenil-Ferguson Lab <https://roszenil.github.io/>
University of Hawaiʻi at Mānoa

**Comment by willgearty** [comment]
That's very bizarre! You're definitely listed as the maintainer, so I'm not sure why you wouldn't have received at least something from CRAN in advance of the removal. Let me know if there's anything I can help with!

**Comment by cmt2** [comment]
Thanks Will! I'm assuming messages went to my spam folder somehow. I'll be
working on this later this week and next.

-------------------
Carrie M. Tribble, PhD <http://carrietribble.weebly.com/> (she/her)
NSF Postdoctoral Fellow, Zenil-Ferguson Lab <https://roszenil.github.io/>
University of Hawaiʻi at Mānoa

**Comment by willgearty** [comment]
Looks like RevGadgets is back up on CRAN, woohoo! It is now included in the Phylogenetics CRAN task view!

**Comment by chlangley** [comment]
In working thru the coalescent tutorials, https://revbayes.github.io/tutorials/coalescent/ I hit upon this issue:

```
> df <- processPopSizes(population_size_log, burnin = burnin, probs = probs, summary = summary, num_grid_points = num_grid_points, max_age = max_age_iso)
Error in processPopSizes(population_size_log, burnin = burnin, probs = probs,  :
  could not find function "processPopSizes"
```


In searching this (all) GitHub I don't find the code for "processPopSizes" .  
I also noted the reference to legacy versions of RevGadgets needed for unspecified tutorials.  I tried installing that referenced legacy version.  But the function is not defined in that version either.  

No doubt I am lost in the mirror room of namespaces. 

Please point me to the appropriate exit.

Thanks in advance.
Chuck
