### ISSUE TITLE
Add density plot distribution in the nodes instead of bars 

### ISSUE THREAD

**Issue by BenjaminGuinet** [revbayes/RevGadgets#17]
Dear RevGadgets developers, I wondered if it was possible to add posterior age distribution in a density plot manner instead of a bar in order to precisely show the distribution of the estimations for each node such as for example this plot : 

<img width="535" alt="Capture d’écran 2023-02-21 à 10 10 59" src="https://user-images.githubusercontent.com/39563212/220300216-3a51de4a-55dc-4594-8feb-56ba69d08a6f.png">

Thank you for your time.

**Comment by cmt2** [comment]
Hi Benjamin, sorry for the delay in responding. This is a fabulous idea, and one that the other developers and I have been toying with for a while. It would require a non-trivial amount of new development. We are aiming for something like this in the next year or so, so stay tuned. But I'm going to close this issue for now, as it isn't a bug report or something that can be easily fixed.
