### ISSUE TITLE
could not find function "plot_branch_rates_tree"

### ISSUE THREAD

**Issue by claudiavaga** [revbayes/RevGadgets#18]
Hi,

I am trying to visualize the branch-specific rates by plotting them using our R package RevGadgets (starting from RevBayes results file), but I am getting this error:

Error in plot_branch_rates_tree(tree_file = my_tree_file, branch_rates_file = my_branch_rates_file) : 
  could not find function "plot_branch_rates_tree"

Someone could indicate me which one is the new  RevGadgets function for doing this?

Thank you!
Claudia

**Comment by mikeryanmay** [comment]
Hi Claudia,

The current version of RevGadgets uses different functions to plot the branch data. See here for an example:

https://revbayes.github.io/tutorials/intro/revgadgets.html#lineage-specific-diversification-analysis <https://revbayes.github.io/tutorials/intro/revgadgets.html#lineage-specific-diversification-analysis>

Hope that helps!

Mike

**Comment by claudiavaga** [comment]
Thank you very much Mike,

It worked!
