### ISSUE TITLE
Add new column information within treedata object to add facets 

### ISSUE THREAD

**Issue by StromTroopers** [revbayes/RevGadgets#8]
Hello, first of all thank you for this package it is very usefull.

I just wrote this post in order to know if  `plotFBDTree` can deal will facet objects ? 

For instance if we take this example : 

```

file <- "data/bears.mcc.tre"

# read in the tree 
tree <- readTrees(paths = file)

# plot the FBD tree
plotFBDTree(tree = tree, 
            timeline = T, 
            geo_units = "epochs",
            tip_labels_italics = T,
            tip_labels_remove_underscore = T,
            tip_labels_size = 3, 
            tip_age_bars = T,
            node_age_bars = T, 
            age_bars_colored_by = "posterior",
            label_sampled_ancs = TRUE) + 
    # use ggplot2 to move the legend and make 
    # the legend background transparent
        theme(legend.position=c(.05, .6),
              legend.background = element_rect(fill="transparent"))
```

We get : 
<img width="556" alt="Capture d’écran 2021-09-17 à 17 45 38" src="https://user-images.githubusercontent.com/38229558/133816791-7e6f969d-3ecd-48a2-84b9-848d7f68d746.png">

and let say we have now another dataframe such as : 

```
labels                  value  color 
Ursus maritimus         5     orange
Ursus arctos            5     orange 
Ursus spelaeus          5     orange 
Ursus thibetanus        5     orange 
Ursus americanus        5     red
Helarctos malayanus     5     red
Melursus ursinus        10    red
Tremarctos ornatus      10    red
Arctodus simus          10    black
Indarctos vireti        10    black
Indarctos arctoides     10    black
Agriarctos spp          10    black
Ailuropoda melanoleuca  10    black 
```

Is it possible to add element within the `list of lists of treedata objects `?  In order to add for instance heatmap using the package `ggheatmap `or to add bars using the  `geom_barh `function from ggplot2 as well ? 

And get something link that for instance ? 

<img width="594" alt="Capture d’écran 2021-09-17 à 17 56 59" src="https://user-images.githubusercontent.com/38229558/133818554-1b83ba46-c3ca-441b-9c0f-22e9c49c07f0.png">

Thanks a lot for your time and have a nice day.

**Comment by cmt2** [comment]
There are a few ways to do this. You can definitely add elements to the `treedata` object:

**Comment by cmt2** [comment]
There are a few ways to do this. You can definitely add to the treedata object. The underlying trait data is stored in a tibble: `tree[[1]][[1]]@data`. You can add columns to that tibble with the additional data. See the [treeio documentation](https://yulab-smu.top/treedata-book/chapter2.html) for more information on how to do this. I will note that deconstructing and converting between a treedata object and a tibble with as_tibble() seems to be a bit buggy with the FBD trees. 

Another option is to use the new [ggtreeExtra package](https://yulab-smu.top/treedata-book/chapter10.html). I played around with this a little bit and was able to get the bar plots, though it might not be exactly what you are looking for: 

```
file <- system.file("extdata", "fbd/bears.mcc.tre", package="RevGadgets")
tree <- readTrees(paths = file)

# other data
df <- data.frame(label = c("Ursus_maritimus", "Ursus_arctos",
                            "Ursus_spelaeus", "Ursus_thibetanus",
                            "Ursus_americanus", "Helarctos_malayanus",
                            "Melursus_ursinus", "Tremarctos_ornatus",
                            "Arctodus_simus", "Indarctos_vireti",
                            "Indarctos_arctoides", "Agriarctos_spp",
                            "Ailuropoda_melanoleuca"),
                 value = c(-5,-5,-5,-5,-5,-5,-10,-10,-10,-10,-10,-10,-10),
                 color = c("orange","orange","orange","orange",
                           "red","red","red","red",
                           "black","black","black","black","black"))



# plot the FBD tree
t <- plotFBDTree(tree = tree, 
            timeline = T, 
            geo_units = "epochs",
            tip_labels_italics = F,
            tip_labels_remove_underscore = F,
            tip_labels_size = 3, 
            tip_age_bars = T,
            node_age_bars = T, 
            age_bars_colored_by = "posterior",
            label_sampled_ancs = TRUE) + 
  # use ggplot2 to move the legend and make 
  # the legend background transparent
  theme(legend.position=c(.05, .6),
        legend.background = element_rect(fill="transparent"))

t +
  geom_fruit(data = df, 
             geom = geom_bar,
             position = position_nudge(x = 10),
             orientation="y",
             fill = "#71c0f9",
             color = "black",
             mapping = aes(x = value, y = label),
             stat="identity") + xlim(-50, 200)
```
![plot_zoom_png](https://user-images.githubusercontent.com/25025386/139753773-4b3cf504-4bdf-4357-a09f-6a3f01583d0f.png)

A few notes on this: 
 

- This seems to plot the data assuming they are in the same units as the tree (hence why I set the numbers to negative -- the x axis is reversed in the FBD plots to show MYA) 
- It's necessary to preserve exact matching between the tip labels and the labels in the data frame. RevGadgets modifies those labels if you set either tip_labels_remove_underscore or tip_labels_italics to TRUE (the default). 
- Positioning is a bit of a challenge, as the plot limits are determined by the geological timescale from deeptime's `coord_geo()`. To get more space on the x axis, you'd have to add the coord_geo() again with wide x limits. I go through how to do this on a video tutorial you can find [here](https://youtu.be/lf7JAKYjFQA?t=5391). 
- I'm still quite new to using ggtreeExtra, but am excited about it's capabilities. I'll probably be adding to RevGadgets and RevGadgets' documentation soon with more working examples of integrating these two packages.
